version: '2'
services:
  mongo-data:
    image: busybox
    container_name: mongo-data
    volumes:
        - /data/db
  mongo:
    image: mongo
    container_name: mongo
    volumes_from:
      - mongo-data
    depends_on:
      - mongo-data
  web-api:
    build:
      context: .
    container_name: web-api
    depends_on:
      - mongo-data
      - mongo
    links:
      - mongo
    ports:
      - "80:8080"